# Generated by Django 3.2.4 on 2021-06-03 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', localflavor.us.models.USPostalCodeField(max_length=2)),
                ('region', models.CharField(choices=[('PIEDMONT', 'Piedmont'), ('MOUTAINS', 'Mountains'), ('COASTAL_PLAIN', 'Coastal Plain')], max_length=100)),
                ('experience_level', models.IntegerField()),
                ('moniker', models.CharField(max_length=240)),
                ('effort_level', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=240, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=240, null=True)),
                ('zone', models.ManyToManyField(related_name='plants', to='garden.GrowingZone')),
            ],
        ),
    ]
