# Generated by Django 3.2.4 on 2021-06-03 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garden', '0002_auto_20210603_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Gardener',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='zone',
        ),
        migrations.DeleteModel(
            name='GrowingZone',
        ),
    ]
