# Generated by Django 3.2.4 on 2021-06-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_auto_20210603_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='color',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='flowering_time',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='moisture_need',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=100),
        ),
    ]
