# Generated by Django 3.2.4 on 2021-06-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_auto_20210603_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('TREE', 'Tree'), ('SHRUB', 'Shrub'), ('FLOWER', 'Flower'), ('GRASS', 'Grass')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='garden.plant')),
            ],
        ),
    ]
